"""Generate pysa/native.pyi so editors can autocomplete cmd.OPCODE names.

Runtime cmd dispatch is intentionally dynamic. This stub gives Pylance,
PyCharm and other language servers a static view without changing runtime code.
"""
from __future__ import annotations

import keyword
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
sys.path.insert(0, str(PYTHON_DIR))

from pysa.signatures import FLAG_COND, PARAM_TYPES, SIGS  # noqa: E402


HEADER = '''"""Static typing stubs for pysa.native.

This file is generated by tools/gen_native_stub.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Any

from .entities import GameObject, Ped, Vehicle
from .enums import (BLIP_SPRITE, CAMERA_MODE, CAR_MISSION, DOOR_LOCK,
                    ENTITY_STATUS, FIGHT_STYLE, GANG, MOVE_STATE, PED_BONE,
                    PICKUP_TYPE, VEHICLE_DOOR, VEHICLE_WHEEL)
from .models import PED_TYPE, VEHICLE, WEAPON
from .ped_models import PED
from .world import EXPLOSION


class _OutMarker: ...


class _EndMarker: ...


class Out:
    INT: _OutMarker
    FLOAT: _OutMarker
    STR: _OutMarker


End: _EndMarker
NOT: int


def signature(name: str) -> str: ...
def doc(name: str) -> str: ...
def find_commands(pattern: str, limit: int = 40) -> list[str]: ...
def call_ex(command: str | int, *args: Any) -> tuple[bool, tuple[Any, ...]]: ...
def call(command: str | int, *args: Any) -> Any: ...
def call_func(addr: int, conv: str = "c", ret: str = "v", spec: str = "", *args: Any) -> Any: ...


class _CommandNamespace:
'''


def safe_param(name: str, index: int, used: set[str]) -> str:
    name = name.strip() or f"arg{index}"
    name = re.sub(r"\W", "_", name)
    if not name or name[0].isdigit():
        name = f"arg_{name}" if name else f"arg{index}"
    if name == "self":
        name = "self_"
    if keyword.iskeyword(name):
        name += "_"
    base = name
    suffix = 2
    while name in used:
        name = f"{base}_{suffix}"
        suffix += 1
    used.add(name)
    return name


TYPED_INPUTS = {
    "bool": "bool",
    "Char": "Ped | int",
    "Car": "Vehicle | int",
    "Heli": "Vehicle | int",
    "Plane": "Vehicle | int",
    "Boat": "Vehicle | int",
    "Train": "Vehicle | int",
    "Trailer": "Vehicle | int",
    "Object": "GameObject | int",
    "WeaponType": "WEAPON | int",
    "model_vehicle": "VEHICLE | int",
    "model_char": "PED | int",
    "PedType": "PED_TYPE | int",
    "MoveState": "MOVE_STATE | int",
    "CarDoor": "VEHICLE_DOOR | int",
    "CarMission": "CAR_MISSION | int",
    "CameraMode": "CAMERA_MODE | int",
    "CarLock": "DOOR_LOCK | int",
    "EntityStatus": "ENTITY_STATUS | int",
    "FightStyle": "FIGHT_STYLE | int",
    "PedBone": "PED_BONE | int",
    "PedBoneId": "PED_BONE | int",
    "GangType": "GANG | int",
    "RadarSprite": "BLIP_SPRITE | int",
    "WheelId": "VEHICLE_WHEEL | int",
    "ExplosionType": "EXPLOSION | int",
    "PickupType": "PICKUP_TYPE | int",
}


def input_type(kind: str, source_type: str = "") -> str:
    if source_type in TYPED_INPUTS:
        return TYPED_INPUTS[source_type]
    if kind == "f":
        return "float"
    if kind == "s":
        return "str"
    if source_type == "any":
        return "Any"
    return "int"


def output_type(kind: str) -> str:
    return {
        "I": "int",
        "F": "float",
        "S": "str",
        "P": "Ped | None",
        "V": "Vehicle | None",
        "O": "GameObject | None",
    }.get(kind, "Any")


def return_type(outspec: str, flags: int) -> str:
    if not outspec:
        return "bool" if flags & FLAG_COND else "None"

    parts = [output_type(kind) for kind in outspec]
    out = parts[0] if len(parts) == 1 else f"tuple[{', '.join(parts)}]"
    if flags & FLAG_COND:
        out = f"{out} | None"
    return out


def method_line(name: str, sig: tuple) -> str:
    _, inspec, outspec, flags, innames, _, doc = sig
    variadic = inspec.endswith("*")
    base = inspec[:-1] if variadic else inspec
    raw_names = innames.split(",") if innames else []
    source_types = PARAM_TYPES.get(name, ())
    used = {"self"}
    params = []
    for index, kind in enumerate(base):
        param_name = safe_param(raw_names[index] if index < len(raw_names) else "", index, used)
        source_type = source_types[index] if index < len(source_types) else ""
        params.append(f"{param_name}: {input_type(kind, source_type)}")
    if variadic:
        params.append("*args: Any")
    joined = ", ".join(["self", *params])
    line = f"    def {name}({joined}) -> {return_type(outspec, flags)}: ..."
    if doc:
        line += f"  # {doc.replace(chr(10), ' ')[:100].rstrip()}"
    return line


def main() -> None:
    out = PYTHON_DIR / "pysa" / "native.pyi"
    lines = [HEADER.rstrip()]
    for name in sorted(SIGS):
        lines.append(method_line(name, SIGS[name]))
    lines.append("")
    lines.append("")
    lines.append("cmd: _CommandNamespace")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
