"""Generate pysa/native.pyi so editors can autocomplete cmd.OPCODE names.

Runtime cmd dispatch is intentionally dynamic. This stub gives Pylance,
PyCharm and other language servers a static view without changing runtime code.
"""
from __future__ import annotations

import keyword
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
sys.path.insert(0, str(PYTHON_DIR))

from pysa.signatures import FLAG_COND, SIGS  # noqa: E402


HEADER = '''"""Static typing stubs for pysa.native.

This file is generated by tools/gen_native_stub.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Any

from .entities import GameObject, Ped, Vehicle


class _OutMarker: ...


class _EndMarker: ...


class Out:
    INT: _OutMarker
    FLOAT: _OutMarker
    STR: _OutMarker


End: _EndMarker
NOT: int


def signature(name: str) -> str: ...
def doc(name: str) -> str: ...
def find_commands(pattern: str, limit: int = 40) -> list[str]: ...
def call_ex(command: str | int, *args: Any) -> tuple[bool, tuple[Any, ...]]: ...
def call(command: str | int, *args: Any) -> Any: ...
def call_func(addr: int, conv: str = "c", ret: str = "v", spec: str = "", *args: Any) -> Any: ...


class _CommandNamespace:
'''


def safe_param(name: str, index: int, used: set[str]) -> str:
    name = name.strip() or f"arg{index}"
    name = re.sub(r"\W", "_", name)
    if not name or name[0].isdigit():
        name = f"arg_{name}" if name else f"arg{index}"
    if name == "self":
        name = "self_"
    if keyword.iskeyword(name):
        name += "_"
    base = name
    suffix = 2
    while name in used:
        name = f"{base}_{suffix}"
        suffix += 1
    used.add(name)
    return name


def input_type(kind: str) -> str:
    if kind == "f":
        return "float"
    if kind == "s":
        return "str"
    return "Any"


def output_type(kind: str) -> str:
    return {
        "I": "int",
        "F": "float",
        "S": "str",
        "P": "Ped | None",
        "V": "Vehicle | None",
        "O": "GameObject | None",
    }.get(kind, "Any")


def return_type(outspec: str, flags: int) -> str:
    if not outspec:
        return "bool" if flags & FLAG_COND else "None"

    parts = [output_type(kind) for kind in outspec]
    out = parts[0] if len(parts) == 1 else f"tuple[{', '.join(parts)}]"
    if flags & FLAG_COND:
        out = f"{out} | None"
    return out


def method_line(name: str, sig: tuple) -> str:
    _, inspec, outspec, flags, innames, _, doc = sig
    variadic = inspec.endswith("*")
    base = inspec[:-1] if variadic else inspec
    raw_names = innames.split(",") if innames else []
    used = {"self"}
    params = []
    for index, kind in enumerate(base):
        param_name = safe_param(raw_names[index] if index < len(raw_names) else "", index, used)
        params.append(f"{param_name}: {input_type(kind)}")
    if variadic:
        params.append("*args: Any")
    joined = ", ".join(["self", *params])
    line = f"    def {name}({joined}) -> {return_type(outspec, flags)}: ..."
    if doc:
        line += f"  # {doc.replace(chr(10), ' ')[:100]}"
    return line


def main() -> None:
    out = PYTHON_DIR / "pysa" / "native.pyi"
    lines = [HEADER.rstrip()]
    for name in sorted(SIGS):
        lines.append(method_line(name, SIGS[name]))
    lines.append("")
    lines.append("")
    lines.append("cmd: _CommandNamespace")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
