"""Typed constants sourced from plugin-sdk's GTA San Andreas enums.

The public names are shortened for Python (`MOVE_STATE.WALK` instead of
`PEDMOVE_WALK`) while retaining the exact numeric values used by the game.
All enums inherit from :class:`int`, so existing APIs and raw commands accept
them without conversion.
"""
from enum import IntEnum, IntFlag


class MOVE_STATE(IntEnum):
    NONE = 0
    STILL = 1
    TURN_LEFT = 2
    TURN_RIGHT = 3
    WALK = 4
    JOG = 5
    RUN = 6
    SPRINT = 7


class CAMERA_MODE(IntEnum):
    NONE = 0x00
    TOP_DOWN = 0x01
    GTA_CLASSIC = 0x02
    BEHIND_CAR = 0x03
    FOLLOW_PED = 0x04
    AIMING = 0x05
    DEBUG = 0x06
    SNIPER = 0x07
    ROCKET_LAUNCHER = 0x08
    MODEL_VIEW = 0x09
    BILL = 0x0A
    SYPHON = 0x0B
    CIRCLE = 0x0C
    CHEESY_ZOOM = 0x0D
    WHEEL = 0x0E
    FIXED = 0x0F
    FIRST_PERSON = 0x10
    FLY_BY = 0x11
    CAM_ON_A_STRING = 0x12
    REACTION = 0x13
    FOLLOW_PED_WITH_BIND = 0x14
    CHRIS = 0x15
    BEHIND_BOAT = 0x16
    PLAYER_FALLEN_WATER = 0x17
    TRAIN_ROOF = 0x18
    RUNNING_SIDE_TRAIN = 0x19
    BLOOD_ON_THE_TRACKS = 0x1A
    PASSENGER = 0x1B
    SYPHON_CRIM_IN_FRONT = 0x1C
    PED_DEAD = 0x1D
    PILLOWS_PAPS = 0x1E
    LOOK_AT_CARS = 0x1F
    ARREST_ONE = 0x20
    ARREST_TWO = 0x21
    M16_FIRST_PERSON = 0x22
    SPECIAL_FIXED_FOR_SYPHON = 0x23
    FIGHT = 0x24
    TOP_DOWN_PED = 0x25
    LIGHTHOUSE = 0x26
    SNIPER_RUNABOUT = 0x27
    ROCKET_LAUNCHER_RUNABOUT = 0x28
    FIRST_PERSON_RUNABOUT = 0x29
    M16_FIRST_PERSON_RUNABOUT = 0x2A
    FIGHT_RUNABOUT = 0x2B
    EDITOR = 0x2C
    HELI_CANNON_FIRST_PERSON = 0x2D
    CAMERA = 0x2E
    ATTACHED = 0x2F
    TWO_PLAYER = 0x30
    TWO_PLAYER_IN_CAR_SHOOTING = 0x31
    TWO_PLAYER_SEPARATE_CARS = 0x32
    HEAT_SEEKING_ROCKET = 0x33
    HEAT_SEEKING_ROCKET_RUNABOUT = 0x34
    AIM_WEAPON = 0x35
    TWO_PLAYER_SEPARATE_CARS_TOP_DOWN = 0x36
    AIM_WEAPON_FROM_CAR = 0x37
    HELI_CHASE = 0x38
    CAM_MAN = 0x39
    BIRD = 0x3A
    PLANE_SPOTTER = 0x3B
    DOG_FIGHT = 0x3C
    FISH = 0x3D
    PLANE_1 = 0x3E
    PLANE_2 = 0x3F
    PLANE_3 = 0x40
    AIM_WEAPON_ATTACHED = 0x41


class DRIVING_STYLE(IntEnum):
    STOP_FOR_CARS = 0
    SLOW_DOWN_FOR_CARS = 1
    AVOID_CARS = 2
    PLOUGH_THROUGH = 3
    STOP_FOR_CARS_IGNORE_LIGHTS = 4


class CAR_MISSION(IntEnum):
    NONE = 0
    CRUISE = 1
    RAM_PLAYER_FARAWAY = 2
    RAM_PLAYER_CLOSE = 3
    BLOCK_PLAYER_FARAWAY = 4
    BLOCK_PLAYER_CLOSE = 5
    BLOCK_PLAYER_HANDBRAKE_STOP = 6
    WAIT_FOR_DELETION = 7
    GOTO_COORDS = 8
    GOTO_COORDS_STRAIGHT = 9
    EMERGENCY_VEHICLE_STOP = 10
    STOP_FOREVER = 11
    GOTO_COORDS_ACCURATE = 12
    GOTO_COORDS_STRAIGHT_ACCURATE = 13
    GOTO_COORDS_AS_THE_CROW_SWIMS = 14
    RAM_CAR_FARAWAY = 15
    RAM_CAR_CLOSE = 16
    BLOCK_CAR_FARAWAY = 17
    BLOCK_CAR_CLOSE = 18
    BLOCK_CAR_HANDBRAKE_STOP = 19
    HELI_FLY_TO_COORDS = 20
    ATTACK_PLAYER = 21
    PLANE_FLY_TO_COORDS = 22
    HELI_LAND = 23
    SLOWLY_DRIVE_TOWARDS_PLAYER_1 = 24
    SLOWLY_DRIVE_TOWARDS_PLAYER_2 = 25
    BLOCK_PLAYER_FORWARD_AND_BACK = 26
    RACING = 33
    FOLLOW_PRE_RECORDED_PATH = 34
    PLANE_ATTACK_PLAYER = 35
    PLANE_FLY_IN_DIRECTION = 36
    PLANE_FOLLOW_ENTITY = 37
    HELI_FOLLOW_ENTITY = 39
    COP_HELI_ATTACK = 40
    POLICE_BIKE = 43
    PARKING_2D = 45
    PARKING_2E = 46
    PARKING_31 = 49
    PARKING_32 = 50
    HELI_KEEP_ENTITY_IN_VIEW = 51
    HELI_CRASH_LAND = 58
    PLANE_HS_MISSILE_ATTACK_CAR = 59
    PLANE_HS_MISSILE_ATTACK_PLAYER = 63
    POLICE_WAIT_FOR_PLAYER = 64


class DOOR_LOCK(IntEnum):
    NOT_USED = 0
    UNLOCKED = 1
    LOCKED = 2
    LOCKOUT_PLAYER_ONLY = 3
    LOCKED_PLAYER_INSIDE = 4
    COP_CAR = 5
    FORCE_SHUT_DOORS = 6
    SKIP_SHUT_DOORS = 7


class VEHICLE_DOOR(IntEnum):
    BONNET = 0
    BOOT = 1
    FRONT_LEFT = 2
    FRONT_RIGHT = 3
    REAR_LEFT = 4
    REAR_RIGHT = 5


class VEHICLE_WHEEL(IntEnum):
    FRONT_LEFT = 0
    REAR_LEFT = 1
    FRONT_RIGHT = 2
    REAR_RIGHT = 3


class LIGHT_OVERRIDE(IntEnum):
    DEFAULT = 0
    FORCE_OFF = 1
    FORCE_ON = 2


class ENTITY_STATUS(IntEnum):
    PLAYER = 0
    PLAYER_PLAYBACK_FROM_BUFFER = 1
    SIMPLE = 2
    PHYSICS = 3
    ABANDONED = 4
    WRECKED = 5
    TRAIN_MOVING = 6
    TRAIN_NOT_MOVING = 7
    HELI = 8
    PLANE = 9
    REMOTE_CONTROLLED = 10
    PLAYER_DISABLED = 11
    TRAILER = 12
    SIMPLE_TRAILER = 13


class FIGHT_STYLE(IntEnum):
    STANDARD = 4
    BOXING = 5
    KUNG_FU = 6
    KNEE_HEAD = 7
    MELEE = 8
    KNIFE = 9
    BAT = 10
    KATANA_CANE = 11
    CHAINSAW = 12
    DILDO = 13
    FLOWER = 14
    GRAB_KICK = 15
    ELBOWS = 16


class PED_BONE(IntEnum):
    PELVIS1 = 1
    PELVIS = 2
    SPINE1 = 3
    UPPER_TORSO = 4
    NECK = 5
    HEAD2 = 6
    HEAD1 = 7
    HEAD = 8
    RIGHT_UPPER_TORSO = 21
    RIGHT_SHOULDER = 22
    RIGHT_ELBOW = 23
    RIGHT_WRIST = 24
    RIGHT_HAND = 25
    RIGHT_THUMB = 26
    LEFT_UPPER_TORSO = 31
    LEFT_SHOULDER = 32
    LEFT_ELBOW = 33
    LEFT_WRIST = 34
    LEFT_HAND = 35
    LEFT_THUMB = 36
    LEFT_HIP = 41
    LEFT_KNEE = 42
    LEFT_ANKLE = 43
    LEFT_FOOT = 44
    RIGHT_HIP = 51
    RIGHT_KNEE = 52
    RIGHT_ANKLE = 53
    RIGHT_FOOT = 54


class GANG(IntEnum):
    BALLAS = 0
    GROVE = 1
    VAGOS = 2
    RIFA = 3
    DA_NANG_BOYS = 4
    MAFIA = 5
    TRIAD = 6
    AZTECAS = 7
    RUSSIAN_MAFIA = 8
    BIKERS = 9


class VEHICLE_CLASS(IntEnum):
    NORMAL = 0
    POOR_FAMILY = 1
    RICH_FAMILY = 2
    EXECUTIVE = 3
    WORKER = 4
    BIG = 5
    TAXI = 6
    MOPED = 7
    MOTORBIKE = 8
    LEISURE_BOAT = 9
    WORKER_BOAT = 10
    BICYCLE = 11
    IGNORE = -1


class VEHICLE_TYPE(IntEnum):
    INVALID = -1
    AUTOMOBILE = 0
    MONSTER_TRUCK = 1
    QUAD = 2
    HELICOPTER = 3
    PLANE = 4
    BOAT = 5
    TRAIN = 6
    FAKE_HELICOPTER = 7
    FAKE_PLANE = 8
    BIKE = 9
    BMX = 10
    TRAILER = 11


class ANIMATION_FLAG(IntFlag):
    STARTED = 0x0001
    LOOPED = 0x0002
    FREEZE_LAST_FRAME = 0x0004
    UNLOCK_LAST_FRAME = 0x0008
    PARTIAL = 0x0010
    MOVEMENT = 0x0020
    TRANSLATE_X = 0x0040
    TRANSLATE_Y = 0x0080
    ADD_TO_BLEND = 0x0400
    FREEZE_TRANSLATION = 0x2000
    BLOCK_REFERENCED = 0x4000
    INDESTRUCTIBLE = 0x8000


class BLIP_SPRITE(IntEnum):
    NONE = 0
    WHITE = 1
    CENTRE = 2
    MAP_HERE = 3
    NORTH = 4
    AIRYARD = 5
    AMMU_NATION = 6
    BARBER = 7
    BIG_SMOKE = 8
    BOATYARD = 9
    BURGER_SHOT = 10
    BULLDOZER = 11
    CATALINA = 12
    CESAR = 13
    CHICKEN = 14
    CJ = 15
    CRASH = 16
    DINER = 17
    EMMET = 18
    ENEMY_ATTACK = 19
    FIRE = 20
    GIRLFRIEND = 21
    HOSPITAL = 22
    SYNDICATE = 23
    MADD_DOGG = 24
    MAFIA_CASINO = 25
    MC_STRAP = 26
    MOD_GARAGE = 27
    OG_LOC = 28
    PIZZA = 29
    POLICE = 30
    PROPERTY_GREEN = 31
    PROPERTY_RED = 32
    RACE = 33
    RYDER = 34
    SAVE_GAME = 35
    SCHOOL = 36
    QUESTION = 37
    SWEET = 38
    TATTOO = 39
    THE_TRUTH = 40
    WAYPOINT = 41
    TORENO_RANCH = 42
    TRIADS = 43
    TRIADS_CASINO = 44
    TSHIRT = 45
    WOOZIE = 46
    ZERO = 47
    DATE_DISCO = 48
    DATE_DRINK = 49
    DATE_FOOD = 50
    TRUCK = 51
    CASH = 52
    FLAG = 53
    GYM = 54
    IMPOUND = 55
    LIGHT = 56
    RUNWAY = 57
    GANG_BLUE = 58
    GANG_PURPLE = 59
    GANG_YELLOW = 60
    GANG_NEUTRAL = 61
    GANG_GREEN = 62
    SPRAY = 63


class EXPLOSION_KIND(IntEnum):
    GRENADE = 0
    MOLOTOV = 1
    ROCKET = 2
    WEAK_ROCKET = 3
    CAR = 4
    QUICK_CAR = 5
    BOAT = 6
    AIRCRAFT = 7
    MINE = 8
    OBJECT = 9
    TANK_FIRE = 10
    SMALL = 11
    RC_VEHICLE = 12


class PICKUP_TYPE(IntEnum):
    NONE = 0
    IN_SHOP = 1
    ON_STREET = 2
    RESPAWNS = 2  # friendly alias for the usual street weapon behavior
    ONCE = 3
    ONCE_TIMEOUT = 4
    ONCE_TIMEOUT_SLOW = 5
    COLLECTABLE = 6
    IN_SHOP_OUT_OF_STOCK = 7
    MONEY = 8
    MINE_INACTIVE = 9
    MINE_ARMED = 10
    NAUTICAL_MINE_INACTIVE = 11
    NAUTICAL_MINE_ARMED = 12
    FLOATING_PACKAGE = 13
    FLOATING_PACKAGE_FLOATING = 14
    ON_STREET_SLOW = 15
    ASSET_REVENUE = 16
    PROPERTY_LOCKED = 17
    PROPERTY_FOR_SALE = 18
    MONEY_PERMANENT = 19
    SNAPSHOT = 20
    TWO_PLAYER = 21
    ONCE_FOR_MISSION = 22
