"""Typed constants sourced from plugin-sdk's GTA San Andreas enums.

The public names are shortened for Python (`MOVE_STATE.WALK` instead of
`PEDMOVE_WALK`) while retaining the exact numeric values used by the game.
All enums inherit from :class:`int`, so existing APIs and raw commands accept
them without conversion.
"""
from enum import IntEnum, IntFlag


class MOVE_STATE(IntEnum):
    NONE = 0
    STILL = 1
    TURN_LEFT = 2
    TURN_RIGHT = 3
    WALK = 4
    JOG = 5
    RUN = 6
    SPRINT = 7


class CAMERA_MODE(IntEnum):
    NONE = 0x00
    TOP_DOWN = 0x01
    GTA_CLASSIC = 0x02
    BEHIND_CAR = 0x03
    FOLLOW_PED = 0x04
    AIMING = 0x05
    DEBUG = 0x06
    SNIPER = 0x07
    ROCKET_LAUNCHER = 0x08
    MODEL_VIEW = 0x09
    BILL = 0x0A
    SYPHON = 0x0B
    CIRCLE = 0x0C
    CHEESY_ZOOM = 0x0D
    WHEEL = 0x0E
    FIXED = 0x0F
    FIRST_PERSON = 0x10
    FLY_BY = 0x11
    CAM_ON_A_STRING = 0x12
    REACTION = 0x13
    FOLLOW_PED_WITH_BIND = 0x14
    CHRIS = 0x15
    BEHIND_BOAT = 0x16
    PLAYER_FALLEN_WATER = 0x17
    TRAIN_ROOF = 0x18
    RUNNING_SIDE_TRAIN = 0x19
    BLOOD_ON_THE_TRACKS = 0x1A
    PASSENGER = 0x1B
    SYPHON_CRIM_IN_FRONT = 0x1C
    PED_DEAD = 0x1D
    PILLOWS_PAPS = 0x1E
    LOOK_AT_CARS = 0x1F
    ARREST_ONE = 0x20
    ARREST_TWO = 0x21
    M16_FIRST_PERSON = 0x22
    SPECIAL_FIXED_FOR_SYPHON = 0x23
    FIGHT = 0x24
    TOP_DOWN_PED = 0x25
    LIGHTHOUSE = 0x26
    SNIPER_RUNABOUT = 0x27
    ROCKET_LAUNCHER_RUNABOUT = 0x28
    FIRST_PERSON_RUNABOUT = 0x29
    M16_FIRST_PERSON_RUNABOUT = 0x2A
    FIGHT_RUNABOUT = 0x2B
    EDITOR = 0x2C
    HELI_CANNON_FIRST_PERSON = 0x2D
    CAMERA = 0x2E
    ATTACHED = 0x2F
    TWO_PLAYER = 0x30
    TWO_PLAYER_IN_CAR_SHOOTING = 0x31
    TWO_PLAYER_SEPARATE_CARS = 0x32
    HEAT_SEEKING_ROCKET = 0x33
    HEAT_SEEKING_ROCKET_RUNABOUT = 0x34
    AIM_WEAPON = 0x35
    TWO_PLAYER_SEPARATE_CARS_TOP_DOWN = 0x36
    AIM_WEAPON_FROM_CAR = 0x37
    HELI_CHASE = 0x38
    CAM_MAN = 0x39
    BIRD = 0x3A
    PLANE_SPOTTER = 0x3B
    DOG_FIGHT = 0x3C
    FISH = 0x3D
    PLANE_1 = 0x3E
    PLANE_2 = 0x3F
    PLANE_3 = 0x40
    AIM_WEAPON_ATTACHED = 0x41


class DRIVING_STYLE(IntEnum):
    STOP_FOR_CARS = 0
    SLOW_DOWN_FOR_CARS = 1
    AVOID_CARS = 2
    PLOUGH_THROUGH = 3
    STOP_FOR_CARS_IGNORE_LIGHTS = 4


class CAR_MISSION(IntEnum):
    NONE = 0
    CRUISE = 1
    RAM_PLAYER_FARAWAY = 2
    RAM_PLAYER_CLOSE = 3
    BLOCK_PLAYER_FARAWAY = 4
    BLOCK_PLAYER_CLOSE = 5
    BLOCK_PLAYER_HANDBRAKE_STOP = 6
    WAIT_FOR_DELETION = 7
    GOTO_COORDS = 8
    GOTO_COORDS_STRAIGHT = 9
    EMERGENCY_VEHICLE_STOP = 10
    STOP_FOREVER = 11
    GOTO_COORDS_ACCURATE = 12
    GOTO_COORDS_STRAIGHT_ACCURATE = 13
    GOTO_COORDS_AS_THE_CROW_SWIMS = 14
    RAM_CAR_FARAWAY = 15
    RAM_CAR_CLOSE = 16
    BLOCK_CAR_FARAWAY = 17
    BLOCK_CAR_CLOSE = 18
    BLOCK_CAR_HANDBRAKE_STOP = 19
    HELI_FLY_TO_COORDS = 20
    ATTACK_PLAYER = 21
    PLANE_FLY_TO_COORDS = 22
    HELI_LAND = 23
    SLOWLY_DRIVE_TOWARDS_PLAYER_1 = 24
    SLOWLY_DRIVE_TOWARDS_PLAYER_2 = 25
    BLOCK_PLAYER_FORWARD_AND_BACK = 26
    RACING = 33
    FOLLOW_PRE_RECORDED_PATH = 34
    PLANE_ATTACK_PLAYER = 35
    PLANE_FLY_IN_DIRECTION = 36
    PLANE_FOLLOW_ENTITY = 37
    HELI_FOLLOW_ENTITY = 39
    COP_HELI_ATTACK = 40
    POLICE_BIKE = 43
    PARKING_2D = 45
    PARKING_2E = 46
    PARKING_31 = 49
    PARKING_32 = 50
    HELI_KEEP_ENTITY_IN_VIEW = 51
    HELI_CRASH_LAND = 58
    PLANE_HS_MISSILE_ATTACK_CAR = 59
    PLANE_HS_MISSILE_ATTACK_PLAYER = 63
    POLICE_WAIT_FOR_PLAYER = 64


class DOOR_LOCK(IntEnum):
    NOT_USED = 0
    UNLOCKED = 1
    LOCKED = 2
    LOCKOUT_PLAYER_ONLY = 3
    LOCKED_PLAYER_INSIDE = 4
    COP_CAR = 5
    FORCE_SHUT_DOORS = 6
    SKIP_SHUT_DOORS = 7


class VEHICLE_DOOR(IntEnum):
    BONNET = 0
    BOOT = 1
    FRONT_LEFT = 2
    FRONT_RIGHT = 3
    REAR_LEFT = 4
    REAR_RIGHT = 5


class VEHICLE_WHEEL(IntEnum):
    FRONT_LEFT = 0
    REAR_LEFT = 1
    FRONT_RIGHT = 2
    REAR_RIGHT = 3


class LIGHT_OVERRIDE(IntEnum):
    DEFAULT = 0
    FORCE_OFF = 1
    FORCE_ON = 2


class ENTITY_STATUS(IntEnum):
    PLAYER = 0
    PLAYER_PLAYBACK_FROM_BUFFER = 1
    SIMPLE = 2
    PHYSICS = 3
    ABANDONED = 4
    WRECKED = 5
    TRAIN_MOVING = 6
    TRAIN_NOT_MOVING = 7
    HELI = 8
    PLANE = 9
    REMOTE_CONTROLLED = 10
    PLAYER_DISABLED = 11
    TRAILER = 12
    SIMPLE_TRAILER = 13


class FIGHT_STYLE(IntEnum):
    STANDARD = 4
    BOXING = 5
    KUNG_FU = 6
    KNEE_HEAD = 7
    MELEE = 8
    KNIFE = 9
    BAT = 10
    KATANA_CANE = 11
    CHAINSAW = 12
    DILDO = 13
    FLOWER = 14
    GRAB_KICK = 15
    ELBOWS = 16


class PED_BONE(IntEnum):
    PELVIS1 = 1
    PELVIS = 2
    SPINE1 = 3
    UPPER_TORSO = 4
    NECK = 5
    HEAD2 = 6
    HEAD1 = 7
    HEAD = 8
    RIGHT_UPPER_TORSO = 21
    RIGHT_SHOULDER = 22
    RIGHT_ELBOW = 23
    RIGHT_WRIST = 24
    RIGHT_HAND = 25
    RIGHT_THUMB = 26
    LEFT_UPPER_TORSO = 31
    LEFT_SHOULDER = 32
    LEFT_ELBOW = 33
    LEFT_WRIST = 34
    LEFT_HAND = 35
    LEFT_THUMB = 36
    LEFT_HIP = 41
    LEFT_KNEE = 42
    LEFT_ANKLE = 43
    LEFT_FOOT = 44
    RIGHT_HIP = 51
    RIGHT_KNEE = 52
    RIGHT_ANKLE = 53
    RIGHT_FOOT = 54


class GANG(IntEnum):
    BALLAS = 0
    GROVE = 1
    VAGOS = 2
    RIFA = 3
    DA_NANG_BOYS = 4
    MAFIA = 5
    TRIAD = 6
    AZTECAS = 7
    RUSSIAN_MAFIA = 8
    BIKERS = 9


class VEHICLE_CLASS(IntEnum):
    NORMAL = 0
    POOR_FAMILY = 1
    RICH_FAMILY = 2
    EXECUTIVE = 3
    WORKER = 4
    BIG = 5
    TAXI = 6
    MOPED = 7
    MOTORBIKE = 8
    LEISURE_BOAT = 9
    WORKER_BOAT = 10
    BICYCLE = 11
    IGNORE = -1


class VEHICLE_TYPE(IntEnum):
    INVALID = -1
    AUTOMOBILE = 0
    MONSTER_TRUCK = 1
    QUAD = 2
    HELICOPTER = 3
    PLANE = 4
    BOAT = 5
    TRAIN = 6
    FAKE_HELICOPTER = 7
    FAKE_PLANE = 8
    BIKE = 9
    BMX = 10
    TRAILER = 11


class ANIMATION_FLAG(IntFlag):
    STARTED = 0x0001
    LOOPED = 0x0002
    FREEZE_LAST_FRAME = 0x0004
    UNLOCK_LAST_FRAME = 0x0008
    PARTIAL = 0x0010
    MOVEMENT = 0x0020
    TRANSLATE_X = 0x0040
    TRANSLATE_Y = 0x0080
    ADD_TO_BLEND = 0x0400
    FREEZE_TRANSLATION = 0x2000
    BLOCK_REFERENCED = 0x4000
    INDESTRUCTIBLE = 0x8000


class BLIP_SPRITE(IntEnum):
    NONE = 0
    WHITE = 1
    CENTRE = 2
    MAP_HERE = 3
    NORTH = 4
    AIRYARD = 5
    AMMU_NATION = 6
    BARBER = 7
    BIG_SMOKE = 8
    BOATYARD = 9
    BURGER_SHOT = 10
    BULLDOZER = 11
    CATALINA = 12
    CESAR = 13
    CHICKEN = 14
    CJ = 15
    CRASH = 16
    DINER = 17
    EMMET = 18
    ENEMY_ATTACK = 19
    FIRE = 20
    GIRLFRIEND = 21
    HOSPITAL = 22
    SYNDICATE = 23
    MADD_DOGG = 24
    MAFIA_CASINO = 25
    MC_STRAP = 26
    MOD_GARAGE = 27
    OG_LOC = 28
    PIZZA = 29
    POLICE = 30
    PROPERTY_GREEN = 31
    PROPERTY_RED = 32
    RACE = 33
    RYDER = 34
    SAVE_GAME = 35
    SCHOOL = 36
    QUESTION = 37
    SWEET = 38
    TATTOO = 39
    THE_TRUTH = 40
    WAYPOINT = 41
    TORENO_RANCH = 42
    TRIADS = 43
    TRIADS_CASINO = 44
    TSHIRT = 45
    WOOZIE = 46
    ZERO = 47
    DATE_DISCO = 48
    DATE_DRINK = 49
    DATE_FOOD = 50
    TRUCK = 51
    CASH = 52
    FLAG = 53
    GYM = 54
    IMPOUND = 55
    LIGHT = 56
    RUNWAY = 57
    GANG_BLUE = 58
    GANG_PURPLE = 59
    GANG_YELLOW = 60
    GANG_NEUTRAL = 61
    GANG_GREEN = 62
    SPRAY = 63


class EXPLOSION_KIND(IntEnum):
    GRENADE = 0
    MOLOTOV = 1
    ROCKET = 2
    WEAK_ROCKET = 3
    CAR = 4
    QUICK_CAR = 5
    BOAT = 6
    AIRCRAFT = 7
    MINE = 8
    OBJECT = 9
    TANK_FIRE = 10
    SMALL = 11
    RC_VEHICLE = 12


class SURFACE(IntEnum):
    """Collision material ids returned by ``world.raycast``."""
    DEFAULT = 0
    TARMAC = 1
    TARMAC_DAMAGED = 2
    TARMAC_BADLY_DAMAGED = 3
    PAVEMENT = 4
    PAVEMENT_DAMAGED = 5
    GRAVEL = 6
    DAMAGED_CONCRETE = 7
    PAINTED_GROUND = 8
    GRASS_SHORT_LUSH = 9
    GRASS_MEDIUM_LUSH = 10
    GRASS_LONG_LUSH = 11
    GRASS_SHORT_DRY = 12
    GRASS_MEDIUM_DRY = 13
    GRASS_LONG_DRY = 14
    GOLF_GRASS_ROUGH = 15
    GOLF_GRASS_SMOOTH = 16
    STEEP_SLIDY_GRASS = 17
    STEEP_CLIFF = 18
    FLOWERBED = 19
    MEADOW = 20
    WASTE_GROUND = 21
    WOODLAND_GROUND = 22
    VEGETATION = 23
    MUD_WET = 24
    MUD_DRY = 25
    DIRT = 26
    DIRT_TRACK = 27
    SAND_DEEP = 28
    SAND_MEDIUM = 29
    SAND_COMPACT = 30
    SAND_ARID = 31
    SAND_MORE = 32
    SAND_BEACH = 33
    CONCRETE_BEACH = 34
    ROCK_DRY = 35
    ROCK_WET = 36
    ROCK_CLIFF = 37
    WATER_RIVERBED = 38
    WATER_SHALLOW = 39
    CORNFIELD = 40
    HEDGE = 41
    WOOD_CRATES = 42
    WOOD_SOLID = 43
    WOOD_THIN = 44
    GLASS = 45
    GLASS_WINDOWS_LARGE = 46
    GLASS_WINDOWS_SMALL = 47
    EMPTY1 = 48
    EMPTY2 = 49
    GARAGE_DOOR = 50
    THICK_METAL_PLATE = 51
    SCAFFOLD_POLE = 52
    LAMP_POST = 53
    METAL_GATE = 54
    METAL_CHAIN_FENCE = 55
    GIRDER = 56
    FIRE_HYDRANT = 57
    CONTAINER = 58
    NEWS_VENDOR = 59
    WHEELBASE = 60
    CARDBOARD_BOX = 61
    PED = 62
    CAR = 63
    CAR_PANEL = 64
    CAR_MOVING_COMPONENT = 65
    TRANSPARENT_CLOTH = 66
    RUBBER = 67
    PLASTIC = 68
    TRANSPARENT_STONE = 69
    WOOD_BENCH = 70
    CARPET = 71
    FLOORBOARD = 72
    STAIRS_WOOD = 73
    P_SAND = 74
    P_SAND_DENSE = 75
    P_SAND_ARID = 76
    P_SAND_COMPACT = 77
    P_SAND_ROCKY = 78
    P_SAND_BEACH = 79
    P_GRASS_SHORT = 80
    P_GRASS_MEADOW = 81
    P_GRASS_DRY = 82
    P_WOODLAND = 83
    P_WOOD_DENSE = 84
    P_ROADSIDE = 85
    P_ROADSIDE_DESERT = 86
    P_FLOWERBED = 87
    P_WASTE_GROUND = 88
    P_CONCRETE = 89
    P_OFFICE_DESK = 90
    P_711_SHELF1 = 91
    P_711_SHELF2 = 92
    P_711_SHELF3 = 93
    P_RESTAURANT_TABLE = 94
    P_BAR_TABLE = 95
    P_UNDERWATER_LUSH = 96
    P_UNDERWATER_BARREN = 97
    P_UNDERWATER_CORAL = 98
    P_UNDERWATER_DEEP = 99
    P_RIVERBED = 100
    P_RUBBLE = 101
    P_BEDROOM_FLOOR = 102
    P_KITCHEN_FLOOR = 103
    P_LIVING_ROOM_FLOOR = 104
    P_CORRIDOR_FLOOR = 105
    P_711_FLOOR = 106
    P_FAST_FOOD_FLOOR = 107
    P_SKANKY_FLOOR = 108
    P_MOUNTAIN = 109
    P_MARSH = 110
    P_BUSHY = 111
    P_BUSHY_MIX = 112
    P_BUSHY_DRY = 113
    P_BUSHY_MID = 114
    P_GRASS_WEE_FLOWERS = 115
    P_GRASS_DRY_TALL = 116
    P_GRASS_LUSH_TALL = 117
    P_GRASS_GREEN_MIX = 118
    P_GRASS_BROWN_MIX = 119
    P_GRASS_LOW = 120
    P_GRASS_ROCKY = 121
    P_GRASS_SMALL_TREES = 122
    P_DIRT_ROCKY = 123
    P_DIRT_WEEDS = 124
    P_GRASS_WEEDS = 125
    P_RIVER_EDGE = 126
    P_POOL_SIDE = 127
    P_FOREST_STUMPS = 128
    P_FOREST_STICKS = 129
    P_FOREST_LEAVES = 130
    P_DESERT_ROCKS = 131
    P_FOREST_DRY = 132
    P_SPARSE_FLOWERS = 133
    P_BUILDING_SITE = 134
    P_DOCKLANDS = 135
    P_INDUSTRIAL = 136
    P_INDUSTRIAL_JETTY = 137
    P_CONCRETE_LITTER = 138
    P_ALLEY_RUBBISH = 139
    P_JUNKYARD_PILES = 140
    P_JUNKYARD_GROUND = 141
    P_DUMP = 142
    P_CACTUS_DENSE = 143
    P_AIRPORT_GROUND = 144
    P_CORNFIELD = 145
    P_GRASS_LIGHT = 146
    P_GRASS_LIGHTER = 147
    P_GRASS_LIGHTER2 = 148
    P_GRASS_MID1 = 149
    P_GRASS_MID2 = 150
    P_GRASS_DARK = 151
    P_GRASS_DARK2 = 152
    P_GRASS_DIRT_MIX = 153
    P_RIVERBED_STONE = 154
    P_RIVERBED_SHALLOW = 155
    P_RIVERBED_WEEDS = 156
    P_SEAWEED = 157
    DOOR = 158
    PLASTIC_BARRIER = 159
    PARK_GRASS = 160
    STAIRS_STONE = 161
    STAIRS_METAL = 162
    STAIRS_CARPET = 163
    FLOOR_METAL = 164
    FLOOR_CONCRETE = 165
    BIN_BAG = 166
    THIN_METAL_SHEET = 167
    METAL_BARREL = 168
    PLASTIC_CONE = 169
    PLASTIC_DUMPSTER = 170
    METAL_DUMPSTER = 171
    WOOD_PICKET_FENCE = 172
    WOOD_SLATTED_FENCE = 173
    WOOD_RANCH_FENCE = 174
    UNBREAKABLE_GLASS = 175
    HAY_BALE = 176
    GORE = 177
    RAIL_TRACK = 178


class PICKUP_TYPE(IntEnum):
    NONE = 0
    IN_SHOP = 1
    ON_STREET = 2
    RESPAWNS = 2  # friendly alias for the usual street weapon behavior
    ONCE = 3
    ONCE_TIMEOUT = 4
    ONCE_TIMEOUT_SLOW = 5
    COLLECTABLE = 6
    IN_SHOP_OUT_OF_STOCK = 7
    MONEY = 8
    MINE_INACTIVE = 9
    MINE_ARMED = 10
    NAUTICAL_MINE_INACTIVE = 11
    NAUTICAL_MINE_ARMED = 12
    FLOATING_PACKAGE = 13
    FLOATING_PACKAGE_FLOATING = 14
    ON_STREET_SLOW = 15
    ASSET_REVENUE = 16
    PROPERTY_LOCKED = 17
    PROPERTY_FOR_SALE = 18
    MONEY_PERMANENT = 19
    SNAPSHOT = 20
    TWO_PLAYER = 21
    ONCE_FOR_MISSION = 22


class MISSION_AUDIO_SLOT(IntEnum):
    SLOT1 = 1
    SLOT2 = 2
    SLOT3 = 3
    SLOT4 = 4
