"""Typed constants sourced from plugin-sdk's GTA San Andreas enums.

The public names are shortened for Python (`MOVE_STATE.WALK` instead of
`PEDMOVE_WALK`) while retaining the exact numeric values used by the game.
All enums inherit from :class:`int`, so existing APIs and raw commands accept
them without conversion.
"""
from enum import IntEnum


class MOVE_STATE(IntEnum):
    NONE = 0
    STILL = 1
    TURN_LEFT = 2
    TURN_RIGHT = 3
    WALK = 4
    JOG = 5
    RUN = 6
    SPRINT = 7


class CAMERA_MODE(IntEnum):
    NONE = 0x00
    TOP_DOWN = 0x01
    GTA_CLASSIC = 0x02
    BEHIND_CAR = 0x03
    FOLLOW_PED = 0x04
    AIMING = 0x05
    DEBUG = 0x06
    SNIPER = 0x07
    ROCKET_LAUNCHER = 0x08
    MODEL_VIEW = 0x09
    BILL = 0x0A
    SYPHON = 0x0B
    CIRCLE = 0x0C
    CHEESY_ZOOM = 0x0D
    WHEEL = 0x0E
    FIXED = 0x0F
    FIRST_PERSON = 0x10
    FLY_BY = 0x11
    CAM_ON_A_STRING = 0x12
    REACTION = 0x13
    FOLLOW_PED_WITH_BIND = 0x14
    CHRIS = 0x15
    BEHIND_BOAT = 0x16
    PLAYER_FALLEN_WATER = 0x17
    TRAIN_ROOF = 0x18
    RUNNING_SIDE_TRAIN = 0x19
    BLOOD_ON_THE_TRACKS = 0x1A
    PASSENGER = 0x1B
    SYPHON_CRIM_IN_FRONT = 0x1C
    PED_DEAD = 0x1D
    PILLOWS_PAPS = 0x1E
    LOOK_AT_CARS = 0x1F
    ARREST_ONE = 0x20
    ARREST_TWO = 0x21
    M16_FIRST_PERSON = 0x22
    SPECIAL_FIXED_FOR_SYPHON = 0x23
    FIGHT = 0x24
    TOP_DOWN_PED = 0x25
    LIGHTHOUSE = 0x26
    SNIPER_RUNABOUT = 0x27
    ROCKET_LAUNCHER_RUNABOUT = 0x28
    FIRST_PERSON_RUNABOUT = 0x29
    M16_FIRST_PERSON_RUNABOUT = 0x2A
    FIGHT_RUNABOUT = 0x2B
    EDITOR = 0x2C
    HELI_CANNON_FIRST_PERSON = 0x2D
    CAMERA = 0x2E
    ATTACHED = 0x2F
    TWO_PLAYER = 0x30
    TWO_PLAYER_IN_CAR_SHOOTING = 0x31
    TWO_PLAYER_SEPARATE_CARS = 0x32
    HEAT_SEEKING_ROCKET = 0x33
    HEAT_SEEKING_ROCKET_RUNABOUT = 0x34
    AIM_WEAPON = 0x35
    TWO_PLAYER_SEPARATE_CARS_TOP_DOWN = 0x36
    AIM_WEAPON_FROM_CAR = 0x37
    HELI_CHASE = 0x38
    CAM_MAN = 0x39
    BIRD = 0x3A
    PLANE_SPOTTER = 0x3B
    DOG_FIGHT = 0x3C
    FISH = 0x3D
    PLANE_1 = 0x3E
    PLANE_2 = 0x3F
    PLANE_3 = 0x40
    AIM_WEAPON_ATTACHED = 0x41


class DRIVING_STYLE(IntEnum):
    STOP_FOR_CARS = 0
    SLOW_DOWN_FOR_CARS = 1
    AVOID_CARS = 2
    PLOUGH_THROUGH = 3
    STOP_FOR_CARS_IGNORE_LIGHTS = 4


class CAR_MISSION(IntEnum):
    NONE = 0
    CRUISE = 1
    RAM_PLAYER_FARAWAY = 2
    RAM_PLAYER_CLOSE = 3
    BLOCK_PLAYER_FARAWAY = 4
    BLOCK_PLAYER_CLOSE = 5
    BLOCK_PLAYER_HANDBRAKE_STOP = 6
    WAIT_FOR_DELETION = 7
    GOTO_COORDS = 8
    GOTO_COORDS_STRAIGHT = 9
    EMERGENCY_VEHICLE_STOP = 10
    STOP_FOREVER = 11
    GOTO_COORDS_ACCURATE = 12
    GOTO_COORDS_STRAIGHT_ACCURATE = 13
    GOTO_COORDS_AS_THE_CROW_SWIMS = 14
    RAM_CAR_FARAWAY = 15
    RAM_CAR_CLOSE = 16
    BLOCK_CAR_FARAWAY = 17
    BLOCK_CAR_CLOSE = 18
    BLOCK_CAR_HANDBRAKE_STOP = 19
    HELI_FLY_TO_COORDS = 20
    ATTACK_PLAYER = 21
    PLANE_FLY_TO_COORDS = 22
    HELI_LAND = 23
    SLOWLY_DRIVE_TOWARDS_PLAYER_1 = 24
    SLOWLY_DRIVE_TOWARDS_PLAYER_2 = 25
    BLOCK_PLAYER_FORWARD_AND_BACK = 26
    RACING = 33
    FOLLOW_PRE_RECORDED_PATH = 34
    PLANE_ATTACK_PLAYER = 35
    PLANE_FLY_IN_DIRECTION = 36
    PLANE_FOLLOW_ENTITY = 37
    HELI_FOLLOW_ENTITY = 39
    COP_HELI_ATTACK = 40
    POLICE_BIKE = 43
    PARKING_2D = 45
    PARKING_2E = 46
    PARKING_31 = 49
    PARKING_32 = 50
    HELI_KEEP_ENTITY_IN_VIEW = 51
    HELI_CRASH_LAND = 58
    PLANE_HS_MISSILE_ATTACK_CAR = 59
    PLANE_HS_MISSILE_ATTACK_PLAYER = 63
    POLICE_WAIT_FOR_PLAYER = 64


class DOOR_LOCK(IntEnum):
    NOT_USED = 0
    UNLOCKED = 1
    LOCKED = 2
    LOCKOUT_PLAYER_ONLY = 3
    LOCKED_PLAYER_INSIDE = 4
    COP_CAR = 5
    FORCE_SHUT_DOORS = 6
    SKIP_SHUT_DOORS = 7


class VEHICLE_DOOR(IntEnum):
    BONNET = 0
    BOOT = 1
    FRONT_LEFT = 2
    FRONT_RIGHT = 3
    REAR_LEFT = 4
    REAR_RIGHT = 5


class VEHICLE_WHEEL(IntEnum):
    FRONT_LEFT = 0
    REAR_LEFT = 1
    FRONT_RIGHT = 2
    REAR_RIGHT = 3


class LIGHT_OVERRIDE(IntEnum):
    DEFAULT = 0
    FORCE_OFF = 1
    FORCE_ON = 2


class ENTITY_STATUS(IntEnum):
    PLAYER = 0
    PLAYER_PLAYBACK_FROM_BUFFER = 1
    SIMPLE = 2
    PHYSICS = 3
    ABANDONED = 4
    WRECKED = 5
    TRAIN_MOVING = 6
    TRAIN_NOT_MOVING = 7
    HELI = 8
    PLANE = 9
    REMOTE_CONTROLLED = 10
    PLAYER_DISABLED = 11
    TRAILER = 12
    SIMPLE_TRAILER = 13


class FIGHT_STYLE(IntEnum):
    STANDARD = 4
    BOXING = 5
    KUNG_FU = 6
    KNEE_HEAD = 7
    MELEE = 8
    KNIFE = 9
    BAT = 10
    KATANA_CANE = 11
    CHAINSAW = 12
    DILDO = 13
    FLOWER = 14
    GRAB_KICK = 15
    ELBOWS = 16
