"""Static callback types for PyAndreas event decorators."""
from __future__ import annotations

from typing import Any, Callable, TypeVar, overload

from .entities import GameObject, Ped, Vehicle
from .models import VEHICLE
from .pad import BUTTON
from .ped_models import PED
from .state_events import (PedDamageEvent, PedDeathEvent, VehicleEnterEvent,
                           VehicleExitEvent, WeaponChangedEvent, ZoneEvent)


_NoArgs = TypeVar("_NoArgs", bound=Callable[[], Any])
_VehicleEvent = TypeVar("_VehicleEvent", bound=Callable[[Vehicle], Any])
_PedEvent = TypeVar("_PedEvent", bound=Callable[[Ped], Any])
_ObjectEvent = TypeVar("_ObjectEvent", bound=Callable[[GameObject], Any])
_VehicleModelEvent = TypeVar(
    "_VehicleModelEvent", bound=Callable[[Vehicle, VEHICLE | int], Any]
)
_PedModelEvent = TypeVar(
    "_PedModelEvent", bound=Callable[[Ped, PED | int], Any]
)
_PedDamageEvent = TypeVar(
    "_PedDamageEvent", bound=Callable[[PedDamageEvent], Any]
)
_PedDeathEvent = TypeVar(
    "_PedDeathEvent", bound=Callable[[PedDeathEvent], Any]
)
_VehicleEnterEvent = TypeVar(
    "_VehicleEnterEvent", bound=Callable[[VehicleEnterEvent], Any]
)
_VehicleExitEvent = TypeVar(
    "_VehicleExitEvent", bound=Callable[[VehicleExitEvent], Any]
)
_WeaponChangedEvent = TypeVar(
    "_WeaponChangedEvent", bound=Callable[[WeaponChangedEvent], Any]
)
_ZoneEvent = TypeVar("_ZoneEvent", bound=Callable[[ZoneEvent], Any])


@overload
def on_tick(fn: _NoArgs, *, ms: None = None) -> _NoArgs: ...
@overload
def on_tick(fn: None = None, *, ms: int) -> Callable[[_NoArgs], _NoArgs]: ...

def on_key(vk: int, trigger: str = "pressed") -> Callable[[_NoArgs], _NoArgs]: ...
def on_button(button: BUTTON | int, trigger: str = "pressed", pad: int = 0) -> Callable[[_NoArgs], _NoArgs]: ...
def on_cheat(word: str) -> Callable[[_NoArgs], _NoArgs]: ...

def on_draw(fn: _NoArgs, /) -> _NoArgs: ...
def on_game_start(fn: _NoArgs, /) -> _NoArgs: ...
def on_game_restart(fn: _NoArgs, /) -> _NoArgs: ...
def on_game_reinit(fn: _NoArgs, /) -> _NoArgs: ...
def on_shutdown(fn: _NoArgs, /) -> _NoArgs: ...
def on_render_init(fn: _NoArgs, /) -> _NoArgs: ...
def on_device_lost(fn: _NoArgs, /) -> _NoArgs: ...
def on_device_reset(fn: _NoArgs, /) -> _NoArgs: ...
def on_pools_init(fn: _NoArgs, /) -> _NoArgs: ...
def on_pools_shutdown(fn: _NoArgs, /) -> _NoArgs: ...
def on_hud_draw(fn: _NoArgs, /) -> _NoArgs: ...
def on_radar_draw(fn: _NoArgs, /) -> _NoArgs: ...
def on_after_fade_draw(fn: _NoArgs, /) -> _NoArgs: ...
def on_menu_draw(fn: _NoArgs, /) -> _NoArgs: ...

def on_vehicle_created(fn: _VehicleEvent, /) -> _VehicleEvent: ...
def on_vehicle_destroyed(fn: _VehicleEvent, /) -> _VehicleEvent: ...
def on_vehicle_render(fn: _VehicleEvent, /) -> _VehicleEvent: ...
def on_vehicle_model_changed(fn: _VehicleModelEvent, /) -> _VehicleModelEvent: ...

def on_ped_created(fn: _PedEvent, /) -> _PedEvent: ...
def on_ped_destroyed(fn: _PedEvent, /) -> _PedEvent: ...
def on_ped_render(fn: _PedEvent, /) -> _PedEvent: ...
def on_ped_model_changed(fn: _PedModelEvent, /) -> _PedModelEvent: ...

def on_object_created(fn: _ObjectEvent, /) -> _ObjectEvent: ...
def on_object_destroyed(fn: _ObjectEvent, /) -> _ObjectEvent: ...
def on_object_render(fn: _ObjectEvent, /) -> _ObjectEvent: ...

def on_ped_damage(fn: _PedDamageEvent, /) -> _PedDamageEvent: ...
def on_ped_death(fn: _PedDeathEvent, /) -> _PedDeathEvent: ...
def on_vehicle_enter(fn: _VehicleEnterEvent, /) -> _VehicleEnterEvent: ...
def on_vehicle_exit(fn: _VehicleExitEvent, /) -> _VehicleExitEvent: ...
def on_weapon_changed(fn: _WeaponChangedEvent, /) -> _WeaponChangedEvent: ...
def on_zone_enter(fn: _ZoneEvent, /) -> _ZoneEvent: ...
def on_zone_exit(fn: _ZoneEvent, /) -> _ZoneEvent: ...
